USE [master]
GO
/****** Object:  Database [dbStokMVC]    Script Date: 01.18.2024 17:55:55 ******/
CREATE DATABASE [dbStokMVC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbStokMVC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\dbStokMVC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbStokMVC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\dbStokMVC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [dbStokMVC] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbStokMVC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dbStokMVC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dbStokMVC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dbStokMVC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dbStokMVC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dbStokMVC] SET ARITHABORT OFF 
GO
ALTER DATABASE [dbStokMVC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dbStokMVC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dbStokMVC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dbStokMVC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dbStokMVC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dbStokMVC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dbStokMVC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dbStokMVC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dbStokMVC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dbStokMVC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [dbStokMVC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dbStokMVC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dbStokMVC] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dbStokMVC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dbStokMVC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dbStokMVC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dbStokMVC] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dbStokMVC] SET RECOVERY FULL 
GO
ALTER DATABASE [dbStokMVC] SET  MULTI_USER 
GO
ALTER DATABASE [dbStokMVC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dbStokMVC] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dbStokMVC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dbStokMVC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [dbStokMVC] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [dbStokMVC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'dbStokMVC', N'ON'
GO
ALTER DATABASE [dbStokMVC] SET QUERY_STORE = OFF
GO

USE [dbStokMVC];
GO

SET ANSI_NULLS ON;
GO

CREATE TABLE [dbo].[TBKULLANCILAR](
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [AD] [varchar](50) NOT NULL,
    [SIFRA] [varchar](50) NOT NULL
    -- Remove the second primary key constraint
) ON [PRIMARY];
GO

/****** Object:  Table [dbo].[TBLKATEGORILER]    Script Date: 01.18.2024 17:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLKATEGORILER](
	[KATEGORIID] [smallint] IDENTITY(1,1) NOT NULL,
	[KATEGORIAD] [varchar](50) NULL,
 CONSTRAINT [PK_TBLKATEGORILER] PRIMARY KEY CLUSTERED 
(
	[KATEGORIID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[TBLMUSTERILER]    Script Date: 01.18.2024 17:55:55 ******/
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLMUSTERILER](
	[MUSTERIID] [int] IDENTITY(1,1) NOT NULL,
	[MUSTERIAD] [varchar](50) NULL,
	[MUSTERISOYAD] [varchar](50) NULL,
 CONSTRAINT [PK_TBLMUSTERILER] PRIMARY KEY CLUSTERED 
(
	[MUSTERIID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[TBLSATISLAR]    Script Date: 01.18.2024 17:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLSATISLAR](
	[SATISID] [int] IDENTITY(1,1) NOT NULL,
	[URUN] [int] NULL,
	[MUSTERI] [int] NULL,
	[ADET] [tinyint] NULL,
	[FIYAT] [decimal](18, 2) NULL,
 CONSTRAINT [PK_TBLSATISLAR] PRIMARY KEY CLUSTERED 
(
	[SATISID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[TBLURUNLER]    Script Date: 01.18.2024 17:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLURUNLER](
	[URUNID] [int] IDENTITY(1,1) NOT NULL,
	[URUNAD] [varchar](50) NULL,
	[MARKA] [varchar](50) NULL,
	[URUNKATEGORI] [smallint] NULL,
	[FIYAT] [decimal](18, 2) NULL,
	[STOK] [tinyint] NULL,
 CONSTRAINT [PK_TBLURUNLER] PRIMARY KEY CLUSTERED 
(
	[URUNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



ALTER TABLE [dbo].[TBLSATISLAR]  WITH CHECK ADD  CONSTRAINT [FK_TBLSATISLAR_TBLMUSTERILER] FOREIGN KEY([MUSTERI])
REFERENCES [dbo].[TBLMUSTERILER] ([MUSTERIID])
GO
ALTER TABLE [dbo].[TBLSATISLAR] CHECK CONSTRAINT [FK_TBLSATISLAR_TBLMUSTERILER]
GO
ALTER TABLE [dbo].[TBLSATISLAR]  WITH CHECK ADD  CONSTRAINT [FK_TBLSATISLAR_TBLURUNLER] FOREIGN KEY([URUN])
REFERENCES [dbo].[TBLURUNLER] ([URUNID])
GO
ALTER TABLE [dbo].[TBLSATISLAR] CHECK CONSTRAINT [FK_TBLSATISLAR_TBLURUNLER]
GO
ALTER TABLE [dbo].[TBLURUNLER]  WITH CHECK ADD  CONSTRAINT [FK_TBLURUNLER_TBLKATEGORILER] FOREIGN KEY([URUNKATEGORI])
REFERENCES [dbo].[TBLKATEGORILER] ([KATEGORIID])
GO
ALTER TABLE [dbo].[TBLURUNLER] CHECK CONSTRAINT [FK_TBLURUNLER_TBLKATEGORILER]
GO
USE [master]
GO
ALTER DATABASE [dbStokMVC] SET  READ_WRITE 
GO